title: CTF FlagFrenzy
email: your-email@example.com
description: >-
  A website dedicated to Capture The Flag challenges and cybersecurity resources.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ctf-flagfreny.github.io" # the base hostname & protocol
github_username: ctf-flagfreny

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/
