# Site settings
title: CTF FlagFrenzy
description: CTF Challenge Platform
url: "https://ctf-flagfreny.github.io"

# Build settings
markdown: kramdown
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag

# Theme customization
show_downloads: false

# Set index file explicitly
index_page: index.mdx

# Include mdx files in processing
include:
  - "*.mdx"

# Exclude from processing
exclude:
  - .github/
  - Gemfile
  - Gemfile.lock
  - vendor/
  - node_modules/
  - README.md  # Exclude README.md from being used as homepage
